### ISSUE TITLE
Attempt to compile DOOM failed

### ISSUE THREAD

**Issue by TrevorSundberg** [MotleyCoderDev/wasm2brs#1]
This was submitted by a user on reddit:
https://www.reddit.com/r/RokuDev/comments/kj3rt4/webassembly_running_on_roku/

```
ubuntu@ip-172-30-0-201:~/wasm2brs$ sudo ./run.sh make doom
Sending build context to Docker daemon   2.56kB
Step 1/16 : FROM ubuntu:20.10
 ---> 671495eee4d8
Step 2/16 : RUN apt-get update &&     apt-get install -y         cmake         clang         lld         git         curl         nodejs         npm         python3         python3-pip         dumb-init
 ---> Using cache
 ---> 1bd1cc8cf945
Step 3/16 : RUN ln /usr/bin/lld /usr/bin/wasm-ld
 ---> Using cache
 ---> b6a71504231d
Step 4/16 : RUN groupadd -g 1000 group && useradd -g 1000 -u 1000 -ms /bin/bash user
 ---> Using cache
 ---> 91053b96bd24
Step 5/16 : USER user
 ---> Using cache
 ---> 935b8e8de6f4
Step 6/16 : WORKDIR /home/user
 ---> Using cache
 ---> 12bd2e47e78c
Step 7/16 : RUN curl https://raw.githubusercontent.com/wasienv/wasienv/master/install.sh |  sh
 ---> Using cache
 ---> f7c051aaa023
Step 8/16 : ENV WASMER_DIR="/home/user/.wasmer"
 ---> Using cache
 ---> 3851f8128cc8
Step 9/16 : ENV WASMER_CACHE_DIR="/home/user/.wasmer/cache"
 ---> Using cache
 ---> da89cabd1c57
Step 10/16 : ENV PATH="/home/user/.wasmer/bin:/home/user/.wasienv/bin/:${PATH}:/home/user/.wasmer/globals/wapm_packages/.bin"
 ---> Using cache
 ---> a1cbd1bfc8e0
Step 11/16 : RUN curl -sSf https://sh.rustup.rs | bash -s -- -y
 ---> Using cache
 ---> 4936ec593469
Step 12/16 : ENV PATH="/home/user/.cargo/bin:${PATH}"
 ---> Using cache
 ---> e6412740fdad
Step 13/16 : RUN rustup target add wasm32-wasi
 ---> Using cache
 ---> 0cb506dec62d
Step 14/16 : RUN cargo install cargo-wasi
 ---> Using cache
 ---> a4c1e93430fa
Step 15/16 : ENTRYPOINT ["/usr/bin/dumb-init", "--"]
 ---> Using cache
 ---> 87f56a418aa0
Step 16/16 : CMD echo "No command specified"
 ---> Using cache
 ---> fbc6afe92c01
Successfully built fbc6afe92c01
Successfully tagged wasm2brs:latest
mkdir -p build/doom
cd build/doom && wasimake cmake ../../samples/doom
Traceback (most recent call last):
  File "/home/user/.wasienv/bin//wasimake", line 33, in <module>
    sys.exit(load_entry_point('wasienv==0.5.4', 'console_scripts', 'wasimake')())
  File "/home/user/.wasienv/bin//wasimake", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.8/importlib/metadata.py", line 504, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.8/importlib/metadata.py", line 177, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: wasienv
make: *** [Makefile:69: build/doom/Makefile] Error 1
```

**Comment by TrevorSundberg** [comment]
This is because docker must be run without `sudo`. Fixed in 7efe434915361073a9afe946a1fe8db713459fe3
